-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.21 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for spd
CREATE DATABASE IF NOT EXISTS `spd` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `spd`;

-- Dumping structure for table spd.setting
CREATE TABLE IF NOT EXISTS `setting` (
  `set_key` varchar(50) DEFAULT NULL,
  `set_val` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table spd.setting: ~59 rows (approximately)
/*!40000 ALTER TABLE `setting` DISABLE KEYS */;
INSERT INTO `setting` (`set_key`, `set_val`) VALUES
	('spd_setting_6371', '{"bps_satker_kode_kab":"054.31.26","bps_city_kab":"Kotabaru","bps_satker_name_kab":"Kabupaten Kotabaru","bps_address_kab":"Jl Jamrud Dirgahayu Pulau Laut Utara","bps_head_kab":"Imam Habib Pamungkas","bps_head_nip_kab":"199301132017011001","bps_ppk_kab":"Pamungkas","bps_ppk_nip_kab":"199501132018011001","bps_bendahara_kab":"Habib","bps_bendahara_nip_kab":"199001132015011001","bps_phone_kab":"(0274) 55711","bps_fax_kab":"(0274) 55711","bps_email_kab":"bps6302@bps.go.id","bps_website_kab":"kotabarukab.bps.go.id","bps_satker_kode_prov":"063.31.260","bps_city_prov":"Banjarbaru","bps_satker_name_prov":"Provinsi Kalimantan Selatan","bps_address_prov":" Jl. Soekarno Hatta\\/Trikora No 7 Banjarbaru, Indonesia","bps_head_prov":"Anto","bps_head_nip_prov":"1","bps_ppk_prov":"Hab","bps_ppk_nip_prov":"2","bps_bendahara_prov":"Oh","bps_bendahara_nip_prov":"3","bps_phone_prov":"(0511) 6749001","bps_fax_prov":"(0511) 6749106","bps_email_prov":"bps63000@bps.go.id","bps_website_prov":"kalsel.bps.go.id","bps_satker_kode_ind":"001.31.260","bps_city_ind":"Jakarta Pusat","bps_satker_name_ind":" ","bps_address_ind":"Jl Dr Soetomo","bps_head_ind":"Yeah","bps_head_nip_ind":"4","bps_ppk_ind":"Bro","bps_ppk_nip_ind":"5","bps_bendahara_ind":"Oke","bps_bendahara_nip_ind":"6","bps_phone_ind":"(62-21) 3841195, 3842508, 3810291","bps_fax_ind":"(62-21) 3857046","bps_email_ind":"bpshq@bps.go.id","bps_website_ind":"bps.go.id"}'),
	('spd_presensi_6371', '{"last_run":1534006312}'),
	('spd_timezone', '{"timezone":"Asia/Makassar"}'),
	('spd_template', '{"kabupaten":"kab","provinsi":"prov","pusat":"ind"}'),
	('spd_surat_number_6371', '{"1":5,"2":"0","3":"0","4":"0","5":"0","6":0}'),
	('spd_presensi_6301', '{"last_run":1534006312}'),
	('spd_setting_6301', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6301', ''),
	('spd_presensi_6302', '{"last_run":1534006312}'),
	('spd_setting_6302', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6302', ''),
	('spd_presensi_6303', '{"last_run":1534006312}'),
	('spd_setting_6303', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6303', ''),
	('spd_presensi_6304', '{"last_run":1534006312}'),
	('spd_setting_6304', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6304', ''),
	('spd_presensi_6305', '{"last_run":1534006312}'),
	('spd_setting_6305', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6305', ''),
	('spd_presensi_6306', '{"last_run":1534006312}'),
	('spd_setting_6306', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6306', ''),
	('spd_presensi_6307', '{"last_run":1534006312}'),
	('spd_setting_6307', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6307', ''),
	('spd_presensi_6308', '{"last_run":1534006312}'),
	('spd_setting_6308', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6308', ''),
	('spd_presensi_6309', '{"last_run":1534006312}'),
	('spd_setting_6309', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6309', ''),
	('spd_presensi_6310', '{"last_run":1534006312}'),
	('spd_setting_6310', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6310', ''),
	('spd_presensi_6311', '{"last_run":1534006312}'),
	('spd_setting_6311', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6311', ''),
	('spd_presensi_6372', '{"last_run":1534006312}'),
	('spd_setting_6372', '{  \n   "bps_satker_kode_kab":"",\n   "bps_city_kab":"",\n   "bps_satker_name_kab":"",\n   "bps_address_kab":"",\n   "bps_head_kab":"",\n   "bps_head_nip_kab":"",\n   "bps_ppk_kab":"",\n   "bps_ppk_nip_kab":"",\n   "bps_bendahara_kab":"",\n   "bps_bendahara_nip_kab":"",\n   "bps_phone_kab":"",\n   "bps_fax_kab":"",\n   "bps_email_kab":"",\n   "bps_website_kab":"",\n   "bps_satker_kode_prov":"",\n   "bps_city_prov":"",\n   "bps_satker_name_prov":"",\n   "bps_address_prov":"",\n   "bps_head_prov":"",\n   "bps_head_nip_prov":"",\n   "bps_ppk_prov":"",\n   "bps_ppk_nip_prov":"",\n   "bps_bendahara_prov":"",\n   "bps_bendahara_nip_prov":"",\n   "bps_phone_prov":"",\n   "bps_fax_prov":"",\n   "bps_email_prov":"",\n   "bps_website_prov":"",\n   "bps_satker_kode_ind":"",\n   "bps_city_ind":"",\n   "bps_satker_name_ind": "",\n   "bps_address_ind":"",\n   "bps_head_ind":"",\n   "bps_head_nip_ind":"",\n   "bps_ppk_ind":"",\n   "bps_ppk_nip_ind":"",\n   "bps_bendahara_ind":"",\n   "bps_bendahara_nip_ind":"",\n   "bps_phone_ind":"",\n   "bps_fax_ind":"",\n   "bps_email_ind":"",\n   "bps_website_ind":""\n}'),
	('spd_surat_number_6372', '\r\n'),
	('spd_presensi_6351', '{"last_run":1534006312}'),
	('spd_setting_6351', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6351', ''),
	('spd_presensi_6352', ''),
	('spd_setting_6352', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6352', ''),
	('spd_presensi_6353', ''),
	('spd_setting_6353', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6353', ''),
	('spd_presensi_6354', ''),
	('spd_setting_6354', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6354', ''),
	('spd_presensi_6355', ''),
	('spd_setting_6355', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6355', ''),
	('spd_presensi_6356', ''),
	('spd_setting_6356', '{  \r\n   "bps_satker_kode_kab":"",\r\n   "bps_city_kab":"",\r\n   "bps_satker_name_kab":"",\r\n   "bps_address_kab":"",\r\n   "bps_head_kab":"",\r\n   "bps_head_nip_kab":"",\r\n   "bps_ppk_kab":"",\r\n   "bps_ppk_nip_kab":"",\r\n   "bps_bendahara_kab":"",\r\n   "bps_bendahara_nip_kab":"",\r\n   "bps_phone_kab":"",\r\n   "bps_fax_kab":"",\r\n   "bps_email_kab":"",\r\n   "bps_website_kab":"",\r\n   "bps_satker_kode_prov":"",\r\n   "bps_city_prov":"",\r\n   "bps_satker_name_prov":"",\r\n   "bps_address_prov":"",\r\n   "bps_head_prov":"",\r\n   "bps_head_nip_prov":"",\r\n   "bps_ppk_prov":"",\r\n   "bps_ppk_nip_prov":"",\r\n   "bps_bendahara_prov":"",\r\n   "bps_bendahara_nip_prov":"",\r\n   "bps_phone_prov":"",\r\n   "bps_fax_prov":"",\r\n   "bps_email_prov":"",\r\n   "bps_website_prov":"",\r\n   "bps_satker_kode_ind":"",\r\n   "bps_city_ind":"",\r\n   "bps_satker_name_ind": "",\r\n   "bps_address_ind":"",\r\n   "bps_head_ind":"",\r\n   "bps_head_nip_ind":"",\r\n   "bps_ppk_ind":"",\r\n   "bps_ppk_nip_ind":"",\r\n   "bps_bendahara_ind":"",\r\n   "bps_bendahara_nip_ind":"",\r\n   "bps_phone_ind":"",\r\n   "bps_fax_ind":"",\r\n   "bps_email_ind":"",\r\n   "bps_website_ind":""\r\n}'),
	('spd_surat_number_6356', '');
/*!40000 ALTER TABLE `setting` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
